### ISSUE TITLE
Calendar days/dates are incorrect

### ISSUE THREAD

**Issue by openstrike** [rjbs/WWW-AdventCalendar#6]
Hello,

In constructing a test calendar for this month (December 2022) the index.html page produced has the wrong days. eg. the 1st of December 2022 is a Thursday but the generated calendar shows it to be a Wednesday.

advent.ini is:

```title = Test Calendar
year = 2022
uri = http://localhost/
category = Perl
editor = Pete

article_dir = src
share_dir = share
```

and after running `advcal -c advent.ini` the tree looks like this:

```.
├── advent.ini
├── out
│   ├── 2022-12-01.html
│   ├── atom.xml
│   ├── index.html
│   └── style.css
├── share
│   └── static
└── src
    └── 2022-12-01.pod
```

but the calendar looks like this:

![image](https://user-images.githubusercontent.com/4331674/205496657-1e82fff5-9fcc-4ac4-abc4-afa4117339a7.png)

which is clearly wrong as it says the 1st is a Wednesday.

(see https://github.com/perladvent/Perl-Advent/issues/257 for the initial issue report)

**Comment by vampirechicken** [comment]
Advent Planet goes out of sync starting in 2016. But I haven't regenerated the earlier years in a while.
