### ISSUE TITLE
Google analytics snippet is out of date

### ISSUE THREAD

**Issue by vampirechicken** [rjbs/WWW-AdventCalendar#9]
G has updated Analytics.
It would be a good thing to update the advent calendar code.

Maybe there's a GA snippet module we can employ, instead of maintaining it in-house...

**Comment by rjbs** [comment]
I regret ever putting tracking code into an advent calendar, and have removed it.

**Comment by vampirechicken** [comment]
Is there a simple way for me to add the analytics code locally without having to maintain a fork?
